title: "Иван Лакериев — DevOps"
description: "CI/CD, Kubernetes, Terraform, AWS. Личный сайт и новости."
url: "https://lkrv69.com"
permalink: pretty
markdown: kramdown
theme: null
plugins:
  - jekyll-seo-tag
  - jekyll-feed
collections:
  posts:
    output: true
defaults:
  - scope: {path: "", type: "posts"}
    values: {layout: post, permalink: /news/:title/}
  - scope: {path: ""}
    values: {layout: default}