backend:
  name: github
  repo: lkrv69/One-Site   # замени на owner/repo сайта
  branch: main
  base_url: https://decap-cms-oauth-client.netlify.app
  auth_endpoint: auth
publish_mode: editorial_workflow
media_folder: "assets/uploads"
public_folder: "/assets/uploads"

site_url: "https://lkrv69.com"
locale: "ru"

collections:
  - name: "posts"
    label: "Новости"
    folder: "_posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Дата", name: "date", widget: "datetime"}
      - {label: "Описание", name: "description", widget: "text", required: false}
      - {label: "Теги", name: "tags", widget: "list", required: false}
      - {label: "Обложка", name: "cover_image", widget: "image", required: false}
      - {label: "Текст", name: "body", widget: "markdown"}
